services:
  - type: web
    name: esus-automation
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      playwright install
      playwright install-deps
    startCommand: gunicorn app:app --timeout 300
