services:
  - type: web
    name: esus-automation
    env: python
    pythonVersion: 3.11.8
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
